name: .Net Deploy Template

on:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o ${{ github.workspace }}/demo 
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ${{ github.workspace }}//demo

  deploy_dev:
    name: Deploy Dev
    runs-on: demo
    environment:
      name: dev 
    needs: build    
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: ${{ github.workspace }}//demo
    
    - run: |
       Xcopy /E /I ${{ github.workspace }}\demo d:\temp /K /D /H /Y
       
